name: Desplegar back a Heroku

on:
  push:
    branches:
      - master
    paths:
      - "tienda-api/**"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Clonar el código a la VM de github
        uses: actions/checkout@v2

      - name: Desplegar el proyecto del Back (Spring)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pineapple-back"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_APP_BASE: "tienda-api"
